spring:
  output:
    ansi:
      enabled: always

server:
  port: 8850

app:
  security:
    token-server-url: http://localhost:9397
    private-key: ${PRIVATE_SECRET}
    client-id: ${CLIENT_ID_SECRET}
  pharmacy:
    url: http://localhost:8080
  supermarket:
    url: http://localhost:7780

security:
  allowed-ips: ${ALLOWED_IPS:127.0.0.1,192.168.1.44}